"""
ctxprotocol.client

Client module for AI Agents to query marketplace and execute tools.
"""

from ctxprotocol.client.client import ContextClient
from ctxprotocol.client.resources.developer import Developer
from ctxprotocol.client.resources.discovery import Discovery
from ctxprotocol.client.resources.query import Query
from ctxprotocol.client.resources.tools import Tools
from ctxprotocol.client.types import (
    AGENT_MODEL_IDS,
    ContextClientOptions,
    ContextError,
    ContextErrorCode,
    DEFAULT_AGENT_MODEL_ID,
    ExecuteApiErrorResponse,
    ExecuteApiSuccessResponse,
    ExecuteMethodInfo,
    ExecuteOptions,
    ExecuteSessionApiSuccessResponse,
    ExecuteSessionResult,
    ExecuteSessionSpend,
    ExecuteSessionStartOptions,
    ExecuteSessionStatus,
    ExecutionResult,
    McpToolMeta,
    McpToolPricingMeta,
    McpToolRateLimitHints,
    McpTool,
    # Query types (pay-per-response)
    QueryApiSuccessResponse,
    QueryChartArtifact,
    QueryChartAxis,
    QueryChartAxisType,
    QueryChartDataValue,
    QueryChartOhlcKeys,
    QueryChartReferenceArea,
    QueryChartReferenceLine,
    QueryChartSeries,
    QueryChartSeriesType,
    QueryChartSpec,
    QueryChartType,
    QueryChartValueFormat,
    QueryComputedArtifact,
    QueryImageArtifact,
    QueryCost,
    QueryCompletenessRepairEvent,
    QueryDeveloperTrace,
    QueryDeveloperTraceDiagnostics,
    QueryDeveloperTraceSummary,
    QueryDeveloperTraceStep,
    QueryDeveloperTraceToolRef,
    QueryJobStartResult,
    QueryJobStatus,
    QueryJobStatusResult,
    QueryOrchestrationMetrics,
    QueryDeveloperTraceLoopInfo,
    QueryStreamDeveloperTraceEvent,
    QueryStreamEvent,
    QueryStreamErrorEvent,
    QueryOptions,
    QueryResult,
    QueryStreamDoneEvent,
    QueryStreamTextDeltaEvent,
    QueryStreamToolStatusEvent,
    QueryToolUsage,
    SearchOptions,
    SearchResponse,
    Tool,
    ToolInfo,
    AgentModelId,
)

__all__ = [
    # Main client
    "ContextClient",
    # Resources
    "Developer",
    "Discovery",
    "Tools",
    "Query",
    # Types
    "ContextClientOptions",
    "AGENT_MODEL_IDS",
    "DEFAULT_AGENT_MODEL_ID",
    "AgentModelId",
    "Tool",
    "McpTool",
    "McpToolMeta",
    "McpToolPricingMeta",
    "McpToolRateLimitHints",
    "SearchResponse",
    "SearchOptions",
    "ExecuteOptions",
    "ExecuteSessionStartOptions",
    "ExecuteSessionStatus",
    "ExecuteSessionSpend",
    "ExecuteSessionResult",
    "ExecutionResult",
    "ExecuteMethodInfo",
    "ExecuteApiSuccessResponse",
    "ExecuteApiErrorResponse",
    "ExecuteSessionApiSuccessResponse",
    "ToolInfo",
    # Query types (pay-per-response)
    "QueryOptions",
    "QueryResult",
    "QueryToolUsage",
    "QueryCost",
    "QueryCompletenessRepairEvent",
    "QueryDeveloperTrace",
    "QueryDeveloperTraceDiagnostics",
    "QueryDeveloperTraceSummary",
    "QueryDeveloperTraceStep",
    "QueryDeveloperTraceToolRef",
    "QueryJobStartResult",
    "QueryJobStatus",
    "QueryJobStatusResult",
    "QueryOrchestrationMetrics",
    "QueryDeveloperTraceLoopInfo",
    "QueryApiSuccessResponse",
    "QueryChartArtifact",
    "QueryChartAxis",
    "QueryChartAxisType",
    "QueryChartDataValue",
    "QueryChartOhlcKeys",
    "QueryChartReferenceArea",
    "QueryChartReferenceLine",
    "QueryChartSeries",
    "QueryChartSeriesType",
    "QueryChartSpec",
    "QueryChartType",
    "QueryChartValueFormat",
    "QueryComputedArtifact",
    "QueryImageArtifact",
    "QueryStreamToolStatusEvent",
    "QueryStreamTextDeltaEvent",
    "QueryStreamDeveloperTraceEvent",
    "QueryStreamDoneEvent",
    "QueryStreamErrorEvent",
    "QueryStreamEvent",
    "ContextErrorCode",
    # Errors
    "ContextError",
]
